protocol: 'https:'
host: 'lab.ueda.tech'
sitetitle: 'CIT自律ロボット研究室'
subtitle: '千葉工業大学 先進工学部 未来ロボティクス学科 上田隆一研究室'
headline:
- text: 'SI2019お疲れ様でした'
twitter:
- account: 'uedalaboratory'
facebook: '@'
hatena: '@'
pocket: '@'
line: '@'
links:
- text: '最新記事'
  href: '/?post'
- text: 'メンバー'
  href: '/?page=member'
- text: '文献'
  href: '/?page=publication'
- text: '講義'
  href: '/?page=lecture'
- text: 'プロジェクト'
  href: '/?page=project'
- text: '共同研究の案内'
  href: '/?page=collaboration_info'
- text: '外部リンク'
  href: '#'
  sublinks:
  - text: '千葉工業大学'
    href: 'https://www.it-chiba.ac.jp/'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/uedalaboratory'
